### ISSUE TITLE
Clarify the measure of income tax

### ISSUE THREAD

**Issue by andkov** [kse-ua/ua-de-center#11]
@izasimovych , the data table you have provisioned( [App 3. Показники  фінансвої спроможності тергромад 1 кв 2022 (в ІАС)](https://docs.google.com/spreadsheets/d/1F2d9EEx46llTMEFtgotzIRmDD0fx9sia/edit?usp=sharing&rtpof=true&sd=true)) contains the measure entitled "ПДФО (грн/1 особу)" in column Z. It's not clear to what time point this measure captures. Please modify the cell Z2 to clarify.

Also, please double-check the accuracy and appropriateness of latinized labels in row 3.

**Comment by izasimovych** [comment]
I don't know the methodology of the calculation for "ПДФО (грн/1 особу)" in column Z so that I did not use this variable for my research. I have calculated ПДФО per capita separately. 

latinized labels seem to be correct

**Comment by andkov** [comment]
Great, thank you, @izasimovych, does this table have all the necessary variables to compute it ourselves?

**Comment by izasimovych** [comment]
Yes, TPI 2020-2021 and Population 2020-2021 are present in the dataset
